AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.12
    Handler: main.lambda_handler

Resources:
  QueryKnowledgeBase:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/query-knowledge-base/
      Timeout: 300
      MemorySize: 2048
      Policies:
        - Statement:
            - Sid: "KnowledgeBaseAccess"
              Effect: "Allow"
              Action: ["bedrock:RetrieveAndGenerate", "bedrock:InvokeModel", "bedrock:Retrieve"]
              Resource: "*"

  SyncKnowledgeBase:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/sync-knowledge-base/
      Timeout: 300
      MemorySize: 2048
      Policies:
        - Statement:
            - Sid: "StartIngestionJob"
              Effect: "Allow"
              Action: ["bedrock:StartIngestionJob", "bedrock:AssociateThirdPartyKnowledgeBase"]
              Resource: "*"